device: "cuda"
model_name: "vit_b_16"
pretrained: true
num_classes: 6

optimizer_name: "AdamW"
lr: 0.0002
weight_decay: 0.001

augmentation: "randaugment"
batch_size: 128
epochs: 50
num_workers: 8

save_dir: "./outputs/vit3_b_16_runs"
log_dir: "./logs/vit3_b_16_runs"

test_model: "resnet50"
test_checkpoint: "./outputs/resnet50_runs/model_epoch_6.0.pth"
